services:
  app:
    container_name: bank-api
    build: .
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: bank-db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bankdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: